export enum AnalyticsEventEnum {
  // Existing events
  ADULT_BANNER_ENTER = "ADULT_BANNER_ENTER",
  ADULT_BANNER_EXIT = "ADULT_BANNER_EXIT",
  CLOSE_AND_PLAY = "CLOSE_AND_PLAY",
  GO_TO_VIDEO = "GO_TO_VIDEO",
  
  // Premium System Events
  PREMIUM_PAGE_VISIT = "PREMIUM_PAGE_VISIT",
  PREMIUM_PAYMENT_STARTED = "PREMIUM_PAYMENT_STARTED",
  PREMIUM_PAYMENT_SUCCESS = "PREMIUM_PAYMENT_SUCCESS",
  PREMIUM_PAYMENT_FAILED = "PREMIUM_PAYMENT_FAILED",
  PREMIUM_VOUCHER_CREATED = "PREMIUM_VOUCHER_CREATED",
  PREMIUM_VOUCHER_VERIFIED = "PREMIUM_VOUCHER_VERIFIED",
  PREMIUM_VOUCHER_INVALID = "PREMIUM_VOUCHER_INVALID",
  PREMIUM_ACCESS_GRANTED = "PREMIUM_ACCESS_GRANTED",
  PREMIUM_ACCESS_DENIED = "PREMIUM_ACCESS_DENIED",
  PREMIUM_SESSION_CREATED = "PREMIUM_SESSION_CREATED",
  PREMIUM_CONTENT_VIEW = "PREMIUM_CONTENT_VIEW",
  
  // Navigation Events
  VIDEO_CARD_CLICK = "VIDEO_CARD_CLICK",
  TAG_CLICK = "TAG_CLICK",
  SEARCH_PERFORMED = "SEARCH_PERFORMED",
  
  // User Engagement
  PAGE_VIEW = "PAGE_VIEW",
  VIDEO_PLAY = "VIDEO_PLAY",
  VIDEO_COMPLETE = "VIDEO_COMPLETE",
  
  // Error Tracking
  API_ERROR = "API_ERROR",
  PAYMENT_ERROR = "PAYMENT_ERROR",
  
  // Content Interaction
  TRENDING_PAGE_VISIT = "TRENDING_PAGE_VISIT",
  TAGS_PAGE_VISIT = "TAGS_PAGE_VISIT",
}
